# -*- coding: utf-8 -*-
"""HackBioikadan1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10uJLvXgYYbaVvbFBjns_jPDa9cghqnd5
"""

Name = "Ika Danjuma Mbateudi"
Email = "ikadanjuma@gmail.com"
Language = "python"
Biostack = "Drug development"
Slack_username = "@ikadan"
print ("name: %s \nEmail: %s \nprogramming Language used: %s \nBiostack username: %s \nSlack username: %s" %(Name, Email, Language, Biostack, Slack_username,))