# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_8akw0sVUPb0VzT4wJc7D6XkHsf1eJi7
"""

Name="Adisa Abdulhakeem Yinka"
Email_address="yinkadisa@gmail.com"
Language="Python"
Biostack="Genomics"
Slack_username="@Haykay"
print("Name:%s\n Email_address:%s\n Language:%s\n Biostack:%s\n Slack_username:%s"%(Name,Email_address,Language,Biostack,Slack_username))