# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jCse-gVO6Z7vO--dwYopHfftSflgJTbk
"""

#personal information
def personal_details():

    Name='Ejeh Jemimah Omaye'

    Email='jemimahomaye@gmail.com'

    Biostack='Genomics'

    Slack_username='@omaye'

    print('Name:{}\n Email:{}\n Biostack:{}\n Slack_username:{}'.format(Name,Email,Biostack,Slack_username))
    
personal_details()