# -*- coding: utf-8 -*-
"""Shekoni_task1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nnQJglZESC6HAxTlfNstcBVhJau10lhZ
"""

print ("Name: Shekoni Olaitan Comfort")
print ("Email: shekoniolaitan77@gmail.com")
print ("Language: Python")
print ("Biostack: Genomics")
print ("Slack_Username: Hollainphinity")