Name = paste( "Umarfaruq", "Olayinka", "Bolaji", sep = " ")
Email <- c( "ubolaji@ksu.edu.sa" )
Language_Used <- paste("R", "Programming", "Language", sep = " ")
Biostack <- paste("Genomics", "and", "Data", "Analytics", sep = " ")
Slack_Username <- c("@UmarFaruq")
Personal = data.frame(Name, Email, Language_Used, Biostack, Slack_Username)
