# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11B2dFA5UhrfC-BB8-nh8Nx70RccC2hOA
"""





"""Name = My name is Iqbal Hossain Nafiz
Email = My email address is nafiz.iqbal27cu@gmail.com
Language = python
Biostack = Vaccine Informatics
Slack username = Nafiz
"""

print ("My name is Iqbal Hossain Nafiz")
print ("My email address is nafiz.iqbal27cu@gmail.com")
print ("The language I used Python")
print ("My Biostack name is Vaccine Informatics")
print ("My Slack user name is Nafiz ")