# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LK3qc09qzDW4OXApeBuWf2JAff3NJYc0
"""

print ("my name is wasiu")
print ("my email address is wasiuabibu@yahoo.com")
print ("The language I used is python")
print ("my biostack is genomics and data analytics")
print ("my slack username is Abibu")
